// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzgNpnZjy_kB4S-iyaNTm_hRunFEYgJRg',
    appId: '1:291201929859:web:6408192a0ac5c9173501b6',
    messagingSenderId: '291201929859',
    projectId: 'music-player-app-11a19',
    authDomain: 'music-player-app-11a19.firebaseapp.com',
    storageBucket: 'music-player-app-11a19.appspot.com',
    measurementId: 'G-BE3N9C3JVW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeYdl8wyMmHPiIlvZ1RR1CZs8fd8cydEw',
    appId: '1:291201929859:android:85576ef445b4d5073501b6',
    messagingSenderId: '291201929859',
    projectId: 'music-player-app-11a19',
    storageBucket: 'music-player-app-11a19.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNs4uWxKM4Dwd-xRY38xtlovjI5ppe-zM',
    appId: '1:291201929859:ios:2d85b956d15d267d3501b6',
    messagingSenderId: '291201929859',
    projectId: 'music-player-app-11a19',
    storageBucket: 'music-player-app-11a19.appspot.com',
    iosBundleId: 'com.example.somniApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNs4uWxKM4Dwd-xRY38xtlovjI5ppe-zM',
    appId: '1:291201929859:ios:2d85b956d15d267d3501b6',
    messagingSenderId: '291201929859',
    projectId: 'music-player-app-11a19',
    storageBucket: 'music-player-app-11a19.appspot.com',
    iosBundleId: 'com.example.somniApp',
  );
}
